[[redirects]]
from = "https://jakubkoralewski.pl"
to = "https://github.com/JakubKoralewski"
status = 301
force = true

[[redirects]]
from = "http://jakubkoralewski.pl"
to = "https://github.com/JakubKoralewski"
status = 301
force = true

[[redirects]]
from = "https://jakubkoralewski.pl/*"
to = "https://github.com/JakubKoralewski"
status = 301
force = true

[[redirects]]
from = "http://jakubkoralewski.pl/*"
to = "https://github.com/JakubKoralewski"
status = 301
force = true

[[redirects]]
from = "http://jakubkoralewski.pl/dziennik"
to = "https://dziennik.netlify.com"
status = 301
force = true

[[redirects]]
from = "https://jakubkoralewski.pl/dziennik"
to = "https://dziennik.netlify.com"
status = 301
force = true

[[redirects]]
from = "http://jakubkoralewski.pl/dziennik_php"
to = "https://dziennik.netlify.com"
status = 301
force = true

[[redirects]]
from = "https://jakubkoralewski.pl/dziennik_php"
to = "https://dziennik.netlify.com"
status = 301
force = true

[[redirects]]
from = "http://jakubkoralewski.pl/dziennik_php_frontend"
to = "https://github.com/JakubKoralewski/dziennik_php_frontend"
status = 301
force = true

[[redirects]]
from = "https://jakubkoralewski.pl/dziennik_php_frontend"
to = "https://github.com/JakubKoralewski/dziennik_php_frontend"
status = 301
force = true


